apiVersion: v1
kind: Namespace
metadata:
  name: probe
---
apiVersion: v1
kind: Pod
metadata:
  name: probe
  namespace: probe
spec:
  containers:
  - name: probe
    image: curlimages/curl:8.8.0
    command: ["sleep", "infinity"]
  restartPolicy: Never
